version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g npm-cli-login
  %{~ if length(env) != 0 ~}
  pre_build:
    commands:
      %{~ for key,val in env ~}
      - "echo '${key}=\"${val}\"' >> ${env_file_name}"
      %{~ endfor ~}
  %{~ endif ~}
  build:
    commands:
      %{~ if do_npm_login ~}
      - npm-cli-login -u $NPM_USER -p $NPM_PASS -e $NPM_EMAIL
      %{~ endif ~}
      - "${build_command}"
artifacts:
  name: BUILD
  base-directory: ${deployment_directory}
  files:
    - '**/*'