version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - "${build_command}"
artifacts:
  name: BUILD
  base-directory: ${deployment_directory}
  files:
    - '**/*'